version: '3.8'

services:
  app_springwithdocker:
    build: SpringWithDocker
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql_beto:3306/mysqlwithdocker?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root
    restart: always
    depends_on:
      mysql_beto:
         condition: service_healthy
  mysql_beto:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mysqlwithdocker
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: